### ISSUE TITLE
scan device 

### ISSUE THREAD

**Issue by Mhde96** [karakusnavy/react-native-bluetooth-serial-lib#1]
hi 

what the difference between this library and react-native-bluetooth-serial

and can i scan nearby device in this library

**Comment by karakusnavy** [comment]
Hello,

The currently live version gives an error. It is the fixed version I published. It works on HC05 module. (LOW BLE MODULES)
Device scan possible.

**Comment by Mhde96** [comment]
but in your installation you have the same name with react-native-bluetooth-serial
how i can install your library

**Comment by karakusnavy** [comment]
download files and
replace with node_modules/react-native-serial-bluetooth files.
